<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RAScriptLanguageServer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' != 'wasi-wasm'">
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'wasi-wasm'">
    <UseAppHost>false</UseAppHost>
    <PublishTrimmed>true</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
    <MSBuildEnableWorkloadResolver>false</MSBuildEnableWorkloadResolver>
    <WasiArgs>--allow-host</WasiArgs>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OmniSharp.Extensions.LanguageServer" Version="0.19.9" />
    <PackageReference Include="RASharp" Version="0.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0"/>
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
  </ItemGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'wasi-wasm'">
    <PackageReference Include="BytecodeAlliance.Componentize.DotNet.Wasm.SDK" Version="0.8.0-preview00011" />
    <PackageReference Include="runtime.linux-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="10.0.0-rc.1.26357.1" />
  </ItemGroup>

</Project>
