name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build Binaries
        run: make build
      - name: Zip Packages
        run: |
          zip rascript-language-server_${{ github.ref_name }}_linux-x64.zip bin/Release/net8.0/linux-x64/publish/rascript-language-server_${{ github.ref_name }}_linux-x64
          zip rascript-language-server_${{ github.ref_name }}_win-x64.zip bin/Release/net8.0/win-x64/publish/rascript-language-server_${{ github.ref_name }}_win-x64.exe
          zip rascript-language-server_${{ github.ref_name }}_osx-x64.zip bin/Release/net8.0/osx-x64/publish/rascript-language-server_${{ github.ref_name }}_osx-x64
          zip rascript-language-server_${{ github.ref_name }}_osx-arm64.zip bin/Release/net8.0/osx-arm64/publish/rascript-language-server_${{ github.ref_name }}_osx-arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: Release tag ${{ github.ref_name }}
          files: |
            rascript-language-server_${{ github.ref_name }}_linux-x64.zip
            rascript-language-server_${{ github.ref_name }}_win-x64.zip
            rascript-language-server_${{ github.ref_name }}_osx-x64.zip
            rascript-language-server_${{ github.ref_name }}_osx-arm64.zip
